# Generated by Django 4.2.5 on 2023-09-26 11:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Manufacture',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Product type',
                'verbose_name_plural': 'Product types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product name')),
                ('vendor_code', models.CharField(max_length=10, unique=True, verbose_name='Vendor code')),
                ('image', models.ImageField(blank=True, default='autoparts/images/default_product.png', null=True, upload_to='autoparts/images/', verbose_name='Image of product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('description', models.TextField(default=None, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='autoparts.manufacturer', verbose_name='Manufacturer')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='autoparts.producttype', verbose_name='Product type')),
            ],
            options={
                'verbose_name': 'Сar spare part',
                'verbose_name_plural': 'Сar spare parts',
                'ordering': ['price', 'quantity'],
            },
        ),
    ]
